[id="con-required-actions_{context}"]
= Required Actions

Required Actions are tasks that a user must finish before they are allowed to log in.  A user must provide credentials before required actions are executed.  Once a required action is completed, the user does not have
to perform the action again.

Admins can add required actions for each individual user within the *Details* tab of the Admin Console.

The required action types:

Update Password:: 
   When set, a user must change their password.

Configure OTP::
   When set, a user must configure a one-time password generator on their mobile device using either the Free OTP or Google Authenticator application.

Verify Email::
   When set, a user must verify that they have a valid email account.  An email will be sent to the user with a link they have to click.  Once this workflow
   is successfully completed, they will be allowed to log in.

Update Profile::
   This required action asks the user to update profile information, such as name, address, email, and phone number.


include::proc-setting-required-actions.adoc[level=+2]
include::proc-setting-default-required-actions.adoc[level=+2]
include::proc-enabling-terms-conditions.adoc[level=+2]




