[id="proc-searching-users_{context}"]
= Searching for users

Search for users to view their detailed information and to understand their role and responsibilities in the console. You can search for a user in the database using the full name, last name, first name, or email address of the user.

.Prerequisites
* You are logged in to the correct realm and are not in the master realm.

.Procedure
. Click *Users* in the left menu bar. This opens the user list page.  
. In the search box, type the full name, last name, firstname, or email address of the user you want to search for in the user database. The serach returns all users that match your criteria.  
. Alternatively, you can click *View all users* to list every user in the system.  
+
NOTE: This will only search the local {project_name} database and not the federated database, such as LDAP. The backends for federated databases do not have a pagination mechanism that enables searching for users. 
+
.. To search users from a federated backend, the user list must be synced into {project_name} database. Adjust the search criteria to sync the backend users into {project_name} database.
+
.. Alternatively, click the *User Federation* tab.
... To apply changes to a selected user, click *Sync changed users* on the page with your federation provider.
... To apply changes to all users in the database, click *Sync all users* on the page with your federation provider.

.Additional resources
* For more information on user federation, see <<_user-storage-federation,User Federation>>.

