[searching-users]
= Searching for users

You can search for a user in the database by using the full name, last name, or email address of the user.

.Prerequisites
* You are logged in to the correct realm and are not in the master realm.

.Procedure
. Click on *Users* in the left menu bar. This will direct you to the user list page.  
. In the search box, type the full name, last name, or email address of the user you want to search for in the user database. The query will bring up all users that match your criteria.  
. Alternatively, you can click *View all users* to list every user in the system.  
+
NOTE: This will only search the local {project_name} database and not the federated database, such as LDAP. The backends for federated databases, such as LDAP, do not have a pagination mechanism that allow for the scanning of users. 
+
.. To search users from a federated backend, the user list must be synced into {project_name} database. Adjust the search criteria to sync the backend users into {project_name} database.
+
.. Alternatively, navigate to the *User Federation* tab.
... To apply changes to a selected user, click *Sync changed users* on the page with your federation provider.
... To apply changes to all users in the database, click *Sync all users* on the page with your federation provider.

.Additional resources
* For more information on user federation, see <<_user-storage-federation,User Federation>>.

